name: CI

permissions: {}

on: # yamllint disable-line rule:truthy
  push:
    branches:
      - main
  pull_request:

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    timeout-minutes: 10
    concurrency:
      group: ${{ github.workflow }}-${{ github.event.pull_request.number ||
        github.ref }}
      cancel-in-progress: true
    permissions:
      contents: read
      packages: read
      statuses: write
    steps:
      - uses: hugoh/gh-workflows/setup@7cbb8fcf3a59c29229d6fd9feb02e46e0a02113a # v1.40.3
      - name: Run tests
        run: mise run test
      - name: Smoke test entry point
        run: uvx --from . spoon-generate-docs --help || true
