name: CI

permissions: {}

on: # yamllint disable-line rule:truthy
  push:
    branches:
      - main
  pull_request:

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    timeout-minutes: 10
    concurrency:
      group: ${{ github.workflow }}-${{ github.event.pull_request.number ||
        github.ref }}
      cancel-in-progress: true
    permissions:
      contents: read
      packages: read
      statuses: write
    steps:
      - uses: hugoh/gh-workflows/setup@7411f5764f11602df3a0e261d428d3e7a69e59a7 # v1.38.2
      - name: Smoke test entry point
        run: uvx --from . spoon-generate-docs --help || true
