name: hk

permissions: {}

on: # yamllint disable-line rule:truthy
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    timeout-minutes: 5
    concurrency:
      group: ${{ github.workflow }}-${{ github.event.pull_request.number ||
        github.ref }}
      cancel-in-progress: true
    permissions:
      contents: read
      packages: read
      statuses: write
    runs-on: ubuntu-latest
    steps:
      - uses: hugoh/gh-workflows/setup@c95078d6578bc039453fc9c865a0bc651dc00982 # v1.40.7
      - name: Sync Python dependencies
        run: uv sync --group dev
      - uses: hugoh/gh-workflows/hk-check@c95078d6578bc039453fc9c865a0bc651dc00982 # v1.40.7
        env:
          PINACT_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
