name: hk

permissions: {}

on: # yamllint disable-line rule:truthy
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    timeout-minutes: 5
    concurrency:
      group: ${{ github.workflow }}-${{ github.event.pull_request.number ||
        github.ref }}
      cancel-in-progress: true
    permissions:
      contents: read
      packages: read
      statuses: write
    runs-on: ubuntu-latest
    steps:
      - uses: hugoh/gh-workflows/setup@30c65c10c5d685575b7c475516b635f79bd128b5 # v1.39.0
      - uses: hugoh/gh-workflows/hk-check@30c65c10c5d685575b7c475516b635f79bd128b5 # v1.39.0
        env:
          PINACT_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
