---
name: semantic-pr

on: # yamllint disable-line rule:truthy
  pull_request:
    types: [opened, edited, reopened, synchronize]

permissions: {}

jobs:
  semantic-pr:
    uses: hugoh/gh-workflows/.github/workflows/semantic-pr.yml@2d58c2d886399dca718e4de89f8c7d0ccd2c749e # v1.38.0
    permissions:
      pull-requests: read
