---
name: semantic-pr

on: # yamllint disable-line rule:truthy
  pull_request:
    types: [opened, edited, reopened, synchronize]

permissions: {}

jobs:
  semantic-pr:
    uses: hugoh/gh-workflows/.github/workflows/semantic-pr.yml@76cbcbdfd23f89a1fb565f4ee4c8964138bc28e7 # v1.40.2
    permissions:
      pull-requests: read
