---
name: semantic-pr

on: # yamllint disable-line rule:truthy
  pull_request:
    types: [opened, edited, reopened, synchronize]

permissions: {}

jobs:
  semantic-pr:
    uses: hugoh/gh-workflows/.github/workflows/semantic-pr.yml@c97fa9d317a76d7deebf849d04d7738cdbc3a7e2 # v1.40.5
    permissions:
      pull-requests: read
