on:
  workflow_call:

permissions:
  contents: read

jobs:
  tag:
    name: Tag
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: write
      actions: write
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Bump version and push tag
        id: tag_bump
        uses: mathieudutour/github-tag-action@a22cf08638b34d5badda920f9daf6e72c477b07b # v6.2
        with:
          github_token: ${{ github.token }}
          default_bump: false

      - name: Trigger release for new tag
        if: steps.tag_bump.outputs.new_tag != ''
        env:
          GH_TOKEN: ${{ github.token }}
          NEW_TAG: ${{ steps.tag_bump.outputs.new_tag }}
        run: gh workflow run release.yml --ref "$NEW_TAG"
