on:
  workflow_call:

permissions:
  contents: read

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
      packages: read
      statuses: write
    steps:
      - uses: hugoh/gh-workflows/setup@5728acd8585f1fa9ab6cda75efe49fce98fb5ac9 # v1.7.0
      - uses: hugoh/gh-workflows/hk-check@5728acd8585f1fa9ab6cda75efe49fce98fb5ac9 # v1.7.0
