on:
  workflow_call:

permissions:
  contents: read

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
      packages: read
      statuses: write
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - uses: jdx/mise-action@e6a8b3978addb5a52f2b4cd9d91eafa7f0ab959d # v4.2.0
        with:
          cache: false
      - name: hk checks
        run: hk check --no-progress --profile ci --all
      - name: Display hk log on failure
        if: failure()
        run: cat /home/runner/.local/state/hk/output.log
