on:
  workflow_call:
    inputs:
      pre_test:
        description: Command to run before tests (e.g. "mise run vendor")
        type: string
        required: false
        default: ""

permissions:
  contents: read

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    timeout-minutes: 10
    concurrency:
      group: ${{ github.workflow }}-${{ github.job }}-${{ github.event.pull_request.number || github.ref }}
      cancel-in-progress: true
    permissions:
      contents: read
    steps:
      - uses: hugoh/gh-workflows/setup@5728acd8585f1fa9ab6cda75efe49fce98fb5ac9 # v1.7.0
      - name: Pre-test
        if: inputs.pre_test != ''
        env:
          PRE_TEST_CMD: ${{ inputs.pre_test }}
        run: $PRE_TEST_CMD
      - name: Run tests
        run: mise run test
